---
title: 'Project 2: Data Mining, Classification, Prediction'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))

class_diag <- function(score, truth, positive, cutoff=.5){

  pred <- factor(score>cutoff,levels=c("TRUE","FALSE"))
  truth <- factor(truth==positive, levels=c("TRUE","FALSE"))

  tab<-table(truth, pred)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[1,1]/rowSums(tab)[1]
  spec=tab[2,2]/rowSums(tab)[2]
  ppv=tab[1,1]/colSums(tab)[1]

#CALCULATE F1
  f1=2*(sens*ppv)/(sens+ppv)
  
#CALCULATE EXACT AUC
  truth<-as.numeric(truth=="TRUE")
  ord<-order(score, decreasing=TRUE)
  score <- score[ord]; truth <- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup<-c(score[-1]>=score[-length(score)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  round(data.frame(acc,sens,spec,ppv,f1,ba=(sens+spec)/2,auc, row.names = "Metrics"),4)
}
```

# Mining, Classification, Prediction

## Annie Nguyen (ahn539)

### Introduction 

Since the turn of the century, health care for women has improved around the world, leading to a 38% decline in maternal mortality between 2000 and 2017. Despite immense strides on the public health front, approximately 810 women died every day from preventable causes related to childbirth and pregnancy in 2017. According to the World Health Organization (WHO), "94% of all maternal deaths occur in low and lower middle-income countries." 
In this project, we will be examining few of the socio-economic variables that may play a role in reducing the maternal mortality ratio: percent of women who decide in their own healthcare, household purchases, and visiting family; percent of general government spending on healthcare; lifetime risk of maternal death in percent; and percent of births attended by healthcare staff. The UN's Sustainable Development Goals (SDG) agenda hopes to reduce the global MMR average to less than 70 per 100,000 births and have no country with a MMR above the average. For simplicity, we will consider a country's MMR as 'reduced' when the value is below 140. Each observation in the data represents a country, and values are recorded over by years

```{R}
library(tidyverse)
library(fivethirtyeight)
UN <- UN
States
Wong
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')
drought <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-20/drought.csv')
```

### Cluster Analysis

```{R}
library(cluster)
clust_mmr<-dat_mmr%>%select(mmr,lifetime_risk,expend_perc) %>% na.omit()
sil_width <- vector()
for(i in 2:10){
  kms <- kmeans(clust_mmr,centers=i)
  sil <- silhouette(kms$cluster,dist(clust_mmr))
  sil_width[i]<- mean(sil[,3])
}
ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name="k",breaks=1:10)
pam_mmr <- clust_mmr %>% pam(k=2)
plot(pam_mmr,which=2)

library(GGally)
clust_mmr %>% mutate(cluster=as.factor(pam_mmr$clustering)) %>% ggpairs(aes(color=cluster))
```

Discussion of clustering here
    
    
### Dimensionality Reduction with PCA

```{R}
# PCA code here
```

Discussions of PCA here. 

###  Linear Classifier

```{R}
# linear classifier code here
```

```{R}
# cross-validation of linear classifier here
```

Discussion here

### Non-Parametric Classifier

```{R}
library(caret)
# non-parametric classifier code here
```

```{R}
# cross-validation of np classifier here
```

Discussion


### Regression/Numeric Prediction

```{R}
# regression model code here
```

```{R}
# cross-validation of regression model here
```

Discussion

### Python 

```{R}
library(reticulate)
```

```{python}
# python code here
```

Discussion

### Concluding Remarks

Include concluding remarks here, if any




